name: Build OpenAPI docs
on:
  push:
    branches:
      - main
      - develop
      - 'release*'
  pull_request:
      types: [opened, reopened, sychronize]
jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 14.x
          # Comes with npm 6. For newer Node, encountered: https://github.com/npm/cli/issues/3359
      - run: npm install -g @redocly/openapi-cli && npm install -g redoc-cli
      - run: npm install -g gh-openapi-docs
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: gh-openapi-docs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          clean: true  # Clean only if on the main branch
          folder: .
