name: Lint and validate OpenAPI specs
on:
  - pull_request:
      types:
      - opened
      - synchronize
      - reopened
jobs:
  lint:
    name: Lint OpenAPI definition
    runs-on: ubuntu-latest
    steps:
      - name: Check out head branch
        uses: actions/checkout@v4
      - name: Run OpenAPI Lint Action
        uses: mhiew/redoc-lint-github-action@v4
        with:
          args: 'openapi/task_execution_service.openapi.yaml'
  diff:
    name: Show OpenAPI differences relative to target branch
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Check out head branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          path: head
      - name: Check out base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: base
      - name: Run OpenAPI Diff Action
        uses: mvegter/openapi-diff-action@v0.23.5
        with:
          head-spec: head/openapi/task_execution_service.openapi.yaml
          base-spec: base/openapi/task_execution_service.openapi.yaml

  validate:
    name: Validate OpenAPI definition
    runs-on: ubuntu-latest
    steps:
      - name: Check out head branch
        uses: actions/checkout@v4
      - name: Run OpenAPI Validate Action
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: openapi/task_execution_service.openapi.yaml
